language: node_js
node_js:
  - stable
branches:
  only:
    - production
    - development
    - main
env:
  - NODE_ENV=test
install: npm install
cache:
  directories:
    - node_modules
script: npm run test:ci
after_success:
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash)
