language: node_js
node_js:
- stable
branches:
  only:
  - main
install: npm install
cache:
  directories:
  - node_modules
script: npm run test:verbose
after_success:
- npm run coverage
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: grT+EjglRcCv5AKSTq+VOOivP90QnxjMR3xF8HXdprAhBrKgWt42JjkNPtzy0L+KwjJL74Ka4UT6RMLpcfLFuXvSlwYlJfywqvNo1mPB77/taYJm/gBEP9ulHR2ubFVn35btLxqkGjBLQBR1CYnhXJt1hH3Xs6MeKbsgHHXycF1IDOhaaLyJB3zW52PNRTxl8pC+IJRLKf5fqBBS0tZu2jciDEjfESBv41HPpWH//Idz/ovbFnNczqvk4R6l4aZhIsakqUvFES9ZNXe64vUgc9wDs9EdjVSaNplLdugFNpU4ZQ2qZDU8c0vzArCMKNBWEwpv7ARr3K/z+4/MdXkgpnuWp+r4qGLBUQzF3F5zRoX6nf0vXiVq2nLzgkpsztzrmn6VXXXR2Ads7n7Sbp4WS/bsXa3werDKFVotKZUtdWzPUrBRld3gjBIKBATm3Gl8Q8PYGRpKrAHWNzUEwdtrxBWtbg3TKmGvEWK7RtT+nBHqhxLOMN4hdI4rrEl3R9QQsDh4EOm+IlWDJL7Gg+2Nd4wn1gt3WPHsjDCAxwxrsB/tDtYeopoOkeG7mBKk6ie2taJwQfhg39FGR3PRgkFGZswjzftTyzKjUZ9gEymJ6LE1qGQQT50BZYurarQQBevbhJkNIgZA8fyslAjGi6d64jaC41qlpznnVlQUyan71/8=
  - secure: RoRTY98xbVcwSf4HINE59DjHuIHuBFsZBaml3lrqS63v9GxPYuSe0QNeHu0eqMUGVEvWHKPmcFccKe9gOhkIuPRZqYUQMdBC3Mm2PXvpa6pZfDxZ3M7ZBNF5IxNKLJAiQq+emPHCnYE5WZ05uOvXbKPuUPuRepsq9WYVhnNaBCKuihhHkEPCf4JzS0lyne+pxe7NTjs+4nIKePCyBJwfy08cleMMOXsLN6Fc4n2UNtK47yrn+DpDS8Xl9UISk1+APo2Cwiljj/6Ao0ezx6b7nSfxCr2vzGPlpoq9bXuVsnsLTnn3fMY6Y24twSQELMejTDt9LtlaUcRAMtRx1NOQYa0OPpr7Gj6EBhzNmH5V6o6TjJvpK51QzbkUFlm3XZoZ/B6dQ3pbqUENcpj+TgQN6Mjf9FdJwfFcJMc/KrqH0WJcQTvglMFPga5AjDH6FXXIPb0w1Aa5HRoEHgFVUSE39CHVc3IvBy2Tpn+rMx2x/TR7RAKxSvqpeWYzRj/rJUiuovO0dx/VNWr5ulB9H3lM+U73/BCWQe+anLk4No4fD0tM0iOIIGfmsYVf0sfaGdZ5tDExRQlmWAAwfqEMP/3IRSEkZHak8WihlNsC2sHGE0dJDbc3k2c1LbS2PWjC/hKlHdSq+7yjUQrunQvjFDfu7WaYCkCwfRqjZ+RwWaHV2MM=
deploy:
  provider: heroku
  api_key:
    secure: PrUVtYEWpzMi+A6+cVNF4jZ2EVt4Urp3xHHbw7YSy3CMln+MJbqd6LCNOE9G75s/FsNIXqsFO+XFKkVP1Ot3nL/Jtla63bEqaD5Z0kW/l5I6DLMD6gorb2DqZqiJ18F2iJRT0wmOc7HKEM8aOZmhaxeNz83y0A2gnOA6x+1DTeaxIy2hSYzGWIqx9lqgc91pcy/kj0WwIw4ishArwzxrcHOzxXerEzpGupv85rfRFzg6I2Fpm1TDp8vKxFCTb0f8+qki9Q/pbndDXqGYPSl0dbU08HR8mZe0Mev8dqWMk3aeqcPIgQTTO+cdC0vGeDM6QJKhTaOmgvVhLAI2iPeUU6u1qkghIJXnc6ayGTkBwnJACKB/mYTGhj5IZKFdBFY7c9tfvx9mFiFnmHWsypelBju2WKyb3qtTHa7Nf3/6WBbwp1zAyolTxDF+hx8COtXV+S7u0bOAZ2WbJ2oAFB+a62zYmGBxybWVK6s2C0pmN4F3qbflm074ycMAA9hq96P8Bacg3kAPQXZfwZSYVvQO+KCs4Aglx9y2zXCMsYKVPKp3pdIgw2a3RFQYd/G+/eDd9Z9zShsShAI0IiUfoZ83p2fJEx6Q3OgIa2EjGosIy83rdK8URVIi13lcaRmvfr6H6CEQdcL7Y2/27mszU0eovtEIutqlS/2zTwdalOxpleU=
  skip_cleanup: true
  app: 
    main: qrobuy
  on:
    branch: main