language: node_js
node_js:
- stable
branches:
  only:
  - main
install: npm install
cache:
  directories:
  - node_modules
script: npm run test:verbose
after_success:
- npm run coverage
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: grT+EjglRcCv5AKSTq+VOOivP90QnxjMR3xF8HXdprAhBrKgWt42JjkNPtzy0L+KwjJL74Ka4UT6RMLpcfLFuXvSlwYlJfywqvNo1mPB77/taYJm/gBEP9ulHR2ubFVn35btLxqkGjBLQBR1CYnhXJt1hH3Xs6MeKbsgHHXycF1IDOhaaLyJB3zW52PNRTxl8pC+IJRLKf5fqBBS0tZu2jciDEjfESBv41HPpWH//Idz/ovbFnNczqvk4R6l4aZhIsakqUvFES9ZNXe64vUgc9wDs9EdjVSaNplLdugFNpU4ZQ2qZDU8c0vzArCMKNBWEwpv7ARr3K/z+4/MdXkgpnuWp+r4qGLBUQzF3F5zRoX6nf0vXiVq2nLzgkpsztzrmn6VXXXR2Ads7n7Sbp4WS/bsXa3werDKFVotKZUtdWzPUrBRld3gjBIKBATm3Gl8Q8PYGRpKrAHWNzUEwdtrxBWtbg3TKmGvEWK7RtT+nBHqhxLOMN4hdI4rrEl3R9QQsDh4EOm+IlWDJL7Gg+2Nd4wn1gt3WPHsjDCAxwxrsB/tDtYeopoOkeG7mBKk6ie2taJwQfhg39FGR3PRgkFGZswjzftTyzKjUZ9gEymJ6LE1qGQQT50BZYurarQQBevbhJkNIgZA8fyslAjGi6d64jaC41qlpznnVlQUyan71/8=
  - secure: RoRTY98xbVcwSf4HINE59DjHuIHuBFsZBaml3lrqS63v9GxPYuSe0QNeHu0eqMUGVEvWHKPmcFccKe9gOhkIuPRZqYUQMdBC3Mm2PXvpa6pZfDxZ3M7ZBNF5IxNKLJAiQq+emPHCnYE5WZ05uOvXbKPuUPuRepsq9WYVhnNaBCKuihhHkEPCf4JzS0lyne+pxe7NTjs+4nIKePCyBJwfy08cleMMOXsLN6Fc4n2UNtK47yrn+DpDS8Xl9UISk1+APo2Cwiljj/6Ao0ezx6b7nSfxCr2vzGPlpoq9bXuVsnsLTnn3fMY6Y24twSQELMejTDt9LtlaUcRAMtRx1NOQYa0OPpr7Gj6EBhzNmH5V6o6TjJvpK51QzbkUFlm3XZoZ/B6dQ3pbqUENcpj+TgQN6Mjf9FdJwfFcJMc/KrqH0WJcQTvglMFPga5AjDH6FXXIPb0w1Aa5HRoEHgFVUSE39CHVc3IvBy2Tpn+rMx2x/TR7RAKxSvqpeWYzRj/rJUiuovO0dx/VNWr5ulB9H3lM+U73/BCWQe+anLk4No4fD0tM0iOIIGfmsYVf0sfaGdZ5tDExRQlmWAAwfqEMP/3IRSEkZHak8WihlNsC2sHGE0dJDbc3k2c1LbS2PWjC/hKlHdSq+7yjUQrunQvjFDfu7WaYCkCwfRqjZ+RwWaHV2MM=
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: lgJVjH41apVN4mhg9sJBFMvkJSXosJ8lOgoUs+LiG9T0O2ANm98xiNn4LCGEJnhSSgq+WK6No+utEvIKMuAVVm1ppfuvrUWkrWf0mWSViCCQug0Pv8a7ipfg6pp6k6i7sGI19NP+UM4LXSQR9Z7+h6c8Ne9KJwfWkL6koO9IRNp5TAEveTRmAhMPKFDUhtw8MwS24WpnL7zpj56Zjg+u5yqmlhLhKy7rggrCuA6+i5mW8Vt7rsnb9DKnNnxV0qwhPILA+1comPAzFUpGFWGP3EO1WiqbfqUyIsq3LivgMMiZxcuIKKiEgt6i93UtKK6lmVvx4m76FuNYa+wMxdN1Scdx+74vgBIWuuE834hk40Q7J10uSGSN0WSPQOs8B9puYgdpW8jcKCpNS6aQMqWxg0Bo5jrXn21RzAf6ncsceZTV8TmdNEzy8L7Zog2e8D4ijjNJ+vBMb3k+QYHQptKO5seaby7YriUg7+GcG0MZEkROZzaafALRM9OgTTYAXLF23GoIKCbEsuAFtI8MgEzbaelSg5elD8RBYEY3ur3RyCkBjYS6BGBllVL4hYjCI/azHnqcLeC57GPZUgabVnbP9bn3C0IxkHEmmzWithbe7PGWir2iQz31AtTT5uoS+LBPAojc1W0yht3ivhUE4e3G8KwN85Rjb+QJGBpcDnjn2Jk=
  app: qrobuy
  on:
    repo: abxsantos/teste-repo
    branch: main
