language: node_js
node_js:
- stable
branches:
  only:
  - main
install: npm install
cache:
  directories:
  - node_modules
script: npm run test:verbose
after_success:
- npm run coverage
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key:
    secure: uV96cr9Q6MMv8SsPf2d1Bwn5GcqNeIfcslykbSIW7ZilyY601wHxeP0AfDH++NH7ASF01FKazMRexBFTriTK5K+Dll1S8ZDtBIab3oUsGf2x7AJExzrd2vsHpN0ZKO/UsG3nvtHw/kOk2tQx1N6kCz6OWGubvtRTa7c4aoHczMx6hPW4NhH4h9bbAoP08wZ3GlpWyA6xKaFKAL3flGb2ILYfzFpP5FJcpvju0jbj+iggDrJabutp5k8W0HEKupOhcorldMk2gYjuVyzHsBACj/gunoSoyfmoT7smi69ubkzxi/pZWKvoYKbo8WmTqkBqegDLmC8m/ZBJaKeCUls5z0c8pGVuFHr+YqQqHoym5WCsBQ1WPDSxRwI/zKMIGrnKBUTZnHEqDyFxcFA5oE4jaIQ24ZDlzFgkYgxTQgM9ryhvNzeT4MPAZ8lxkeqOb64L958i9FrpsQDGeDUiCraphNElMMK4cVJjerlfw9eODfD39RSTcuhGXE0kF1cF1nAfweY9YhMWxvgIYHkBq58wSHNA4Y13M3HqP6G2xrI+KoIwccIGeGHXqgdHTIb2vh5Qy5cR0GJCcjpoLHTxkpqLFsrN5nu3tTAVKm9zGIVH5zDdhZwMiH+khpTd09uohbv9DeQ9fBPrLmiB8asm8AEb7+BIMu+STWNDMloNHTskQa4=
  app: qrobuy-backend
  skip_cleanup: true
  on:
    branch: main
env:
  global:
  - secure: grT+EjglRcCv5AKSTq+VOOivP90QnxjMR3xF8HXdprAhBrKgWt42JjkNPtzy0L+KwjJL74Ka4UT6RMLpcfLFuXvSlwYlJfywqvNo1mPB77/taYJm/gBEP9ulHR2ubFVn35btLxqkGjBLQBR1CYnhXJt1hH3Xs6MeKbsgHHXycF1IDOhaaLyJB3zW52PNRTxl8pC+IJRLKf5fqBBS0tZu2jciDEjfESBv41HPpWH//Idz/ovbFnNczqvk4R6l4aZhIsakqUvFES9ZNXe64vUgc9wDs9EdjVSaNplLdugFNpU4ZQ2qZDU8c0vzArCMKNBWEwpv7ARr3K/z+4/MdXkgpnuWp+r4qGLBUQzF3F5zRoX6nf0vXiVq2nLzgkpsztzrmn6VXXXR2Ads7n7Sbp4WS/bsXa3werDKFVotKZUtdWzPUrBRld3gjBIKBATm3Gl8Q8PYGRpKrAHWNzUEwdtrxBWtbg3TKmGvEWK7RtT+nBHqhxLOMN4hdI4rrEl3R9QQsDh4EOm+IlWDJL7Gg+2Nd4wn1gt3WPHsjDCAxwxrsB/tDtYeopoOkeG7mBKk6ie2taJwQfhg39FGR3PRgkFGZswjzftTyzKjUZ9gEymJ6LE1qGQQT50BZYurarQQBevbhJkNIgZA8fyslAjGi6d64jaC41qlpznnVlQUyan71/8=
  - secure: RoRTY98xbVcwSf4HINE59DjHuIHuBFsZBaml3lrqS63v9GxPYuSe0QNeHu0eqMUGVEvWHKPmcFccKe9gOhkIuPRZqYUQMdBC3Mm2PXvpa6pZfDxZ3M7ZBNF5IxNKLJAiQq+emPHCnYE5WZ05uOvXbKPuUPuRepsq9WYVhnNaBCKuihhHkEPCf4JzS0lyne+pxe7NTjs+4nIKePCyBJwfy08cleMMOXsLN6Fc4n2UNtK47yrn+DpDS8Xl9UISk1+APo2Cwiljj/6Ao0ezx6b7nSfxCr2vzGPlpoq9bXuVsnsLTnn3fMY6Y24twSQELMejTDt9LtlaUcRAMtRx1NOQYa0OPpr7Gj6EBhzNmH5V6o6TjJvpK51QzbkUFlm3XZoZ/B6dQ3pbqUENcpj+TgQN6Mjf9FdJwfFcJMc/KrqH0WJcQTvglMFPga5AjDH6FXXIPb0w1Aa5HRoEHgFVUSE39CHVc3IvBy2Tpn+rMx2x/TR7RAKxSvqpeWYzRj/rJUiuovO0dx/VNWr5ulB9H3lM+U73/BCWQe+anLk4No4fD0tM0iOIIGfmsYVf0sfaGdZ5tDExRQlmWAAwfqEMP/3IRSEkZHak8WihlNsC2sHGE0dJDbc3k2c1LbS2PWjC/hKlHdSq+7yjUQrunQvjFDfu7WaYCkCwfRqjZ+RwWaHV2MM=
