language: node_js
node_js:
- stable
branches:
  only:
  - main
install: npm install
cache:
  directories:
  - node_modules
script: npm run test:verbose
after_success:
- npm run coverage
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: grT+EjglRcCv5AKSTq+VOOivP90QnxjMR3xF8HXdprAhBrKgWt42JjkNPtzy0L+KwjJL74Ka4UT6RMLpcfLFuXvSlwYlJfywqvNo1mPB77/taYJm/gBEP9ulHR2ubFVn35btLxqkGjBLQBR1CYnhXJt1hH3Xs6MeKbsgHHXycF1IDOhaaLyJB3zW52PNRTxl8pC+IJRLKf5fqBBS0tZu2jciDEjfESBv41HPpWH//Idz/ovbFnNczqvk4R6l4aZhIsakqUvFES9ZNXe64vUgc9wDs9EdjVSaNplLdugFNpU4ZQ2qZDU8c0vzArCMKNBWEwpv7ARr3K/z+4/MdXkgpnuWp+r4qGLBUQzF3F5zRoX6nf0vXiVq2nLzgkpsztzrmn6VXXXR2Ads7n7Sbp4WS/bsXa3werDKFVotKZUtdWzPUrBRld3gjBIKBATm3Gl8Q8PYGRpKrAHWNzUEwdtrxBWtbg3TKmGvEWK7RtT+nBHqhxLOMN4hdI4rrEl3R9QQsDh4EOm+IlWDJL7Gg+2Nd4wn1gt3WPHsjDCAxwxrsB/tDtYeopoOkeG7mBKk6ie2taJwQfhg39FGR3PRgkFGZswjzftTyzKjUZ9gEymJ6LE1qGQQT50BZYurarQQBevbhJkNIgZA8fyslAjGi6d64jaC41qlpznnVlQUyan71/8=
  - secure: RoRTY98xbVcwSf4HINE59DjHuIHuBFsZBaml3lrqS63v9GxPYuSe0QNeHu0eqMUGVEvWHKPmcFccKe9gOhkIuPRZqYUQMdBC3Mm2PXvpa6pZfDxZ3M7ZBNF5IxNKLJAiQq+emPHCnYE5WZ05uOvXbKPuUPuRepsq9WYVhnNaBCKuihhHkEPCf4JzS0lyne+pxe7NTjs+4nIKePCyBJwfy08cleMMOXsLN6Fc4n2UNtK47yrn+DpDS8Xl9UISk1+APo2Cwiljj/6Ao0ezx6b7nSfxCr2vzGPlpoq9bXuVsnsLTnn3fMY6Y24twSQELMejTDt9LtlaUcRAMtRx1NOQYa0OPpr7Gj6EBhzNmH5V6o6TjJvpK51QzbkUFlm3XZoZ/B6dQ3pbqUENcpj+TgQN6Mjf9FdJwfFcJMc/KrqH0WJcQTvglMFPga5AjDH6FXXIPb0w1Aa5HRoEHgFVUSE39CHVc3IvBy2Tpn+rMx2x/TR7RAKxSvqpeWYzRj/rJUiuovO0dx/VNWr5ulB9H3lM+U73/BCWQe+anLk4No4fD0tM0iOIIGfmsYVf0sfaGdZ5tDExRQlmWAAwfqEMP/3IRSEkZHak8WihlNsC2sHGE0dJDbc3k2c1LbS2PWjC/hKlHdSq+7yjUQrunQvjFDfu7WaYCkCwfRqjZ+RwWaHV2MM=
deploy:
  provider: heroku
  api_key:
    secure: TQcO7ETl1InMonBvc2I1M0c0vJhnIXB+MEmjAgSuTyyIsleiHi1HEGOYDUsFoGWqkVEOpTNBrzZgIclx1NaiH9dGgV+G3HuZGFhpMZaMpktGbdHAFHMZGaCHnGxsL+Bb8GSO4aaLk5SMy/NYuKUIVRkf4c+S7RcW+bKD+lCXoHOvOpRVWtj0y7ksb5JzVYeIZRyYs4u9/xxLyu7gqofzUglmkJQtAL+wje9qHR/w0vqou9u0AJEawssr6NdPJdO1EPw2kaEG2zQykzlG6RUrVNV3Oy/6z6shmZwrUkH8fUF7EaomHmuXc1NUtdZtnE4FukSP1qKJAdf1aplizGYgKUHisbIgDwMUWk6AOddD2sWZuLzXG08teWwuL4s97iYEbxSiFEtoujsD2021JOSMX9j1LyTXlvlXpOXPPEsoeiwKDleZ+TNK1GD2AQXT6pJxGL36G5zHWfM8xvXYWUOVYGRkT3HekhBR5MmVdv7FQ/WKKvImG9NKnXGskeMv+f8U7GmQIvDzTIWelKAOJzd3wxgbqJ5+gJ3wg05XerpEiliItO9o3HL2TlI3klEYwZ1uhlHLz4e6whLHIO3Rjrd47ah0NGCp2HJCjVNw/Dsxy+hy3cCUkV5xXWGz9nJ5CC9N/kqhUalEXMEM4ekQUQrtiqa+TcA5rnIL2h8l2X3wbb4=
  skip_cleanup: true
  app: qrobuy
