version: "3.8"

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongodbnetwork

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      - mongodbnetwork
    links:
      - mongo

volumes:
  mongo:

networks:
  mongodbnetwork:
    driver: bridge
